name: PvP
version: 1.0.1-35bdbf5
author: uni
main: br.com.plutomc.pvp.arena.GameMain
softdepend: [ProtocolLib]
description: PvP Bukkit Plugin based on core, core-bukkit and game-engine
website: www.plutomc.com.br