  name: Arcade
  main: br.com.plutomc.duels.scrim.GameMain
  version: 1.0.0-324f612
  author: uni
  description: Arcade Bukkit Plugin, based on core, core-bukkit and game-engine
  website: www.plutomc.com.br
