name: login
version: 1.0.0-c1ff2f7
main: br.com.plutomc.lobby.login.LoginMain
softdepend: [ProtocolLib]
website: www.plutomc.com.br
description: Login Bukkit Plugin based on core, core-bukkit and lobby-core
