  name: Arcade
  main: br.com.plutomc.duels.gapple.GameMain
  version: 1.0.0-2a6a60f
  author: uni
  description: Arcade Bukkit Plugin, based on core, core-bukkit and game-engine
  website: www.plutomc.com.br
