name: Arcade
version: 0.0.1-development-f8f29a0
main: br.com.plutomc.game.bedwars.GameMain
softdepend: [ProtocolLib]
website: www.plutomc.com.br
description: Arcade Bukkit Plugin based on core, core-bukkit and game-engine
