name: Arcade
version: 0.0.1-0d1735c
main: br.com.plutomc.game.bedwars.GameMain
softdepend: [ProtocolLib]
website: www.plutomc.com.br
description: Arcade Bukkit Plugin based on core, core-bukkit and game-engine
