name: Lobby
version: 1.0.0-7360f5a
main: br.com.plutomc.lobby.main.LobbyMain
softdepend: [ProtocolLib]
website: www.plutomc.com.br
description: Lobby Bukkit Plugin based on core, core-bukkit and lobby-core
