name: Lobby
version: 1.0.0-dev
main: br.com.plutomc.lobby.duels.LobbyMain
softdepend: [ProtocolLib]
website: www.plutomc.com.br
description: Lobby Bukkit Plugin based on core, core-bukkit and lobby-core
